PES-239 - Desenvolver a modal de mudar status do usuário
FaculdadeSenaiJoinville/penelope pull request #22
Opened 2021-08-20 02:37 UTC by englernicolas

2021-08-23 23:22 UTC, gabrielSBorges commented
Falta mudar a versão do dictionary no package do penelope

2021-08-23 23:23 UTC, gabrielSBorges requested changes

2021-08-23 23:23 UTC, gabrielSBorges commented on pages/users/update-status.vue
> +				<h1>Deseja mesmo alterar o status do usuário para '{{ nextStatus }}'?</h1>
isso pode ser uma message em Dictionary.users

2021-08-24 23:38 UTC, gabrielSBorges approved these changes

2021-08-24 23:39 UTC, tchiteu submitted a review, later dismissed

2021-08-24 23:50 UTC, gabrielSBorges approved these changes

2021-08-25 00:02 UTC, tchiteu approved these changes

2021-08-25 00:02 UTC, merged