PES-243 - Tela de listagem de usuários
FaculdadeSenaiJoinville/penelope pull request #32
Opened 2021-09-23 23:15 UTC by tchiteu

2021-09-25 20:05 UTC, gabrielSBorges commented
Vercel cobrando já pra fazer o deploy kkkkkkk

2021-09-25 20:20 UTC, gabrielSBorges commented
![image](https://user-images.githubusercontent.com/32948255/134785022-206f860f-4825-4543-a371-87df8529951c.png)
O "editar status" não seria removido pra deixar editar o status pela modal de edit mesmo?

2021-09-25 20:36 UTC, gabrielSBorges commented
![image](https://user-images.githubusercontent.com/32948255/134785381-454251c4-24d2-4ac4-a9c4-4c1a3844d0d2.png)
esse botão da lixeirinha pode ser retirado, o edit do status vai ficar na modal de edit mesmo pra simplificar a tela

2021-09-25 20:47 UTC, englernicolas reviewed
Fiz alguns comentários

2021-09-25 20:47 UTC, englernicolas commented on layouts/default.vue
> +	<VApp>
Viltifu tá quebrando tudo :cry:

2021-09-25 20:47 UTC, englernicolas commented on pages/users/index.vue
> +			<OButton success title="novo" :action="openNewUserModal">
Ali não seria "new"? Ou a tradução

2021-09-25 20:47 UTC, englernicolas commented on pages/users/index.vue
> +				no-data-text="Nada encontrado"
Uma sugestão é adicionar esses textos no dictionary

2021-09-25 20:53 UTC, gabrielSBorges requested changes

2021-09-25 20:53 UTC, gabrielSBorges commented on plugins/global.mixin.ts
> +					config.params = query;
aqui deixa dentro do IF mesmo, como o query é não obrigatório ele pode ir "undefined", aí sei lá se pode dar ruim no axios por isso kkkkkkk

![image](https://user-images.githubusercontent.com/32948255/134785476-d090ce84-1756-41f3-b0f9-e8b1bf854bf3.png)

2021-09-25 20:53 UTC, gabrielSBorges commented on plugins/global.mixin.ts
> +					const config: AxiosConfigObject = { };
👀

2021-09-25 20:53 UTC, gabrielSBorges commented on pages/users/index.vue
> +
espacito sobrando

2021-09-25 20:53 UTC, gabrielSBorges commented on pages/users/index.vue
> +				try {
try catch?

pq não usa o "then", "catch" "finally" das promises mesmo?

2021-09-25 20:53 UTC, gabrielSBorges commented on pages/users/index.vue
> +			actionButtons(id: string) {
isso tu poderia fazer dentro do "findUsers", antes do "this.users = users" da linha 163, tu poderia fazer um for pra setar e adicionar uma propriedade "actionButtons" em cada usuário, aí lá no componente tu passa ":buttons="item.actionButtons""

2021-09-25 21:00 UTC, gabrielSBorges commented on pages/users/index.vue
> +			<OButton success title="novo" :action="openNewUserModal">
iiih rapaz pior que faltou o Dictionary aí hein kkkkkkk

2021-09-25 21:14 UTC, gabrielSBorges commented on pages/users/index.vue
> +						title: 'Coordenador',
é bom pegar a tradução pra esses enums ao invés de passar um valor fixo. Nesse caso 'ADMIN' é 'Administrador', não 'Coordenador'. Aí no filtro ta aparecendo uma coisa e na tabela outra

2021-09-29 23:38 UTC, gabrielSBorges approved these changes

2021-09-29 23:57 UTC, englernicolas approved these changes

2021-09-30 00:18 UTC, englernicolas approved these changes

2021-09-30 22:44 UTC, gabrielSBorges approved these changes

2021-09-30 22:54 UTC, merged